#pragma once
#include <GLFW/glfw3.h>

#define VIPER_MOUSE_BUTTON_1         0
#define VIPER_MOUSE_BUTTON_2         1
#define VIPER_MOUSE_BUTTON_3         2
#define VIPER_MOUSE_BUTTON_4         3
#define VIPER_MOUSE_BUTTON_5         4
#define VIPER_MOUSE_BUTTON_6         5
#define VIPER_MOUSE_BUTTON_7         6
#define VIPER_MOUSE_BUTTON_8         7
#define VIPER_MOUSE_BUTTON_LAST      GLFW_MOUSE_BUTTON_8
#define VIPER_MOUSE_BUTTON_LEFT      GLFW_MOUSE_BUTTON_1
#define VIPER_MOUSE_BUTTON_RIGHT     GLFW_MOUSE_BUTTON_2
#define VIPER_MOUSE_BUTTON_MIDDLE    GLFW_MOUSE_BUTTON_3

enum MouseButton {
    BUTTON_1 = VIPER_MOUSE_BUTTON_1,
    BUTTON_2 = VIPER_MOUSE_BUTTON_2,
    BUTTON_3 = VIPER_MOUSE_BUTTON_3,
    BUTTON_4 = VIPER_MOUSE_BUTTON_4,
    BUTTON_5 = VIPER_MOUSE_BUTTON_5,
    BUTTON_6 = VIPER_MOUSE_BUTTON_6,
    BUTTON_7 = VIPER_MOUSE_BUTTON_7,
    BUTTON_8 = VIPER_MOUSE_BUTTON_8,

    BUTTON_LAST = VIPER_MOUSE_BUTTON_LAST,
    BUTTON_LEFT = VIPER_MOUSE_BUTTON_LEFT,
    BUTTON_RIGHT = VIPER_MOUSE_BUTTON_RIGHT,
    BUTTON_MIDDLE = VIPER_MOUSE_BUTTON_MIDDLE
};